# html lang
language: zh

# canvas 动态背景
canvas_dust: true

# <body> 背景图片链接
background_image: https://ak.hypergryph.com/assets/index/images/ak/pc/bk.jpg # /img/bg.jpg

# 侧边栏
aside:
  in_left: true # 侧边栏在左 true / false
  logo: https://ak.hypergryph.com/assets/index/images/ak/pc/faction/1.png # 图片链接，建议 1:1 比例
  dr: / # 侧边栏 Dr. 链接
  copyright: # 版权声明、备案号等，可自定义键值，不想显示则留空
    ©:
    ICP:

# post 文章页面配置；true / false
post:
  date: true # 是否显示发布日期
  updated: true # 是否显示修改日期
  source: false # 是否显示源文件路径
  word_count: false # 是否显示字数统计
  reading_time: false # 是否显示预计阅读时长
  excerpt: true # 是否在文章中显示摘要内容（<!-- more--> 以上的内容）
  reward: true # 文章末显示打赏二维码
# 文章内目录
toc:
  list_number: true # true / false ；是否显示编号
  max_depth: 6 # 最大目录深度
  min_depth: 1 # 最小目录深度
# 归档页；true / false
archives:
  categories_count: true # 是否显示分类总数
  tags_count: true # 是否显示标签总数

# 搜索框
search:
  enable: true

# Valine 无后端评论系统
valine:
  enable: false
  app_id: # APP ID
  app_key: # APP KEY
  server_url: # APP DOMAIN（LeanCloud 国际版）

gitalk:
  enable: false
  client_id: # GitHub Application Client ID
  client_secret: # GitHub Application Client Secret
  repo: # GitHub repository
  owner: # GitHub repository owner
  admin: [] # GitHub repository owner and collaborators (Users who having write access to this repository)
            # Example: [adminA,adminB]
  id: # (optional) The unique id of the page
      # Example: location.pathname

# 图表支持
mermaid:
  enable: false
  version: '8.13.5'

# pjax 支持 —— 实验性测试阶段，请谨慎开启
pjax:
  enable: false
  version: '0.2.8'

# 公式支持
mathjax:
  enable: false
  version: '2.6.1'

katex:
  enable: true

# main menu navigation
menu:
  Home: ''
#  About: about/
#  Contact: contact/
  Archives: archives/

# stylesheets loaded in the <head>
stylesheets:
- //unpkg.com/@highlightjs/cdn-assets@11.4.0/styles/atom-one-dark-reasonable.min.css

# scripts loaded in the end of the body
scripts:
- //unpkg.com/@highlightjs/cdn-assets@11.4.0/highlight.min.js
